await update.message.reply_text(
    "🔥 ACESSO VIP +18 LIBERADO HOJE 🔥\n\n"
    "Conteúdo exclusivo 🔞\n"
    "Atualizações diárias 😈\n"
    "Acesso imediato após confirmação 💎\n\n"
    "⚠️ Vagas limitadas hoje.\n\n"
    "Quer garantir seu acesso agora?\n"
    "Responda: SIM ou NAO"
)await update.message.reply_text(
    "🔥 ACESSO VIP +18 LIBERADO HOJE 🔥\n\n"
    "Conteúdo exclusivo 🔞\n"
    "Atualizações diárias 😈\n"
    "Acesso imediato após confirmação 💎\n\n"
    "⚠️ Vagas limitadas hoje.\n\n"
    "Quer garantir seu acesso agora?\n"
    "Responda: SIM ou NAO"
)await update.message.reply_text(
    "💎 Perfeito, vou te explicar rápido:\n\n"
    "Hoje o acesso está saindo por apenas R$19,99.\n"
    "Pagamento via PIX.\n\n"
    "🔐 Envie para a chave abaixo:\n"
    "11948212565\n\n"
    "Assim que pagar, envie:\n"
    "PAGUEI\n\n"
    "⚠️ Liberação imediata após confirmação."
)await update.message.reply_text(
    "🔥 Pagamento confirmado com sucesso!\n\n"
    "Aqui está seu acesso VIP:\n"
    "https://t.me/+ETimjCvSzUc4YWZh\n\n"
    "Bem-vindo(a) 😈 Aproveite."
)
